---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - defaults
dependencies:
  - coreutils  # for sort, uniq
  - gawk       # for awk processing