# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "concat_bed"
description: Concatenate, clean, sort and deduplicate multiple BED files
keywords:
  - bed
  - concatenate
  - sort
  - deduplicate
  - structural variants
tools:
  - custom:
      description: |
        Custom script using standard Unix tools (cat, awk, sort, uniq) to 
        process BED files containing structural variant regions.
      homepage: https://www.gnu.org/software/coreutils/
      documentation: https://www.gnu.org/software/coreutils/manual/

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - beds:
        type: file
        description: List of BED files to concatenate
        pattern: "*.bed"

output:
  - bed:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.bed":
          type: file
          description: Concatenated, sorted and deduplicated BED file
          pattern: "*.bed"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"


authors:
  - "@saramenasantamaria"
maintainers:
  - "@saramenasantamaria"