name: "SETGT"
description: "Fix missing genotype calls in VCF files by replacing ./. with 0/0"
keywords:
  - "vcf"
  - "fix"
  - "missing"
  - "genotype"

tools:
  - "bcftools":
      description: "A set of utilities that manipulate variant calls in the Variant Call Format (VCF) and its binary counterpart BCF format."
      homepage: "https://samtools.github.io/bcftools/bcftools.html"
      documentation: "http://www.htslib.org/doc/bcftools.html"
      doi: "10.1093/gigascience/giab008"
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: file
      description: Input VCF file
      pattern: "*.{vcf,vcf.gz}"
  - tbi:
      type: file
      description: Index of the input VCF file
      pattern: "*.{tbi,csi}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: file
      description: Fixed VCF file with missing genotypes replaced by 0/0
      pattern: "*.vcf.gz"
  - tbi:
      type: file
      description: Index of the fixed VCF file
      pattern: "*.vcf.gz.tbi"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@saramenasantamaria"
maintainers:
  - "@saramenasantamaria"