# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "gvcf_combine"
description: Perform GVCF combination and joint genotyping operations to combine family trio GVCFs into a single VCF.
keywords:
  - gvcf
  - vcf
  - genotyping
  - joint-calling
  - gatk
  - family
  - trio
components:
  - gatk4/combinegvcfs
  - gatk4/genotypegvcfs
  - gatk4/variantfiltration
  - bcftools/annotate

input:
  - ch_gvcfs:
      type: channel
      description: |
        Channel containing family metadata, list of GVCF files and their tabix indices
        Structure: [ meta, gvcfs, tbis ]
        Where meta is a Groovy Map containing family information
        e.g. [ id:'family_001', proband_id:'proband_001', mother_id:'mother_001', father_id:'father_001', sv_p:'path/to/proband', sv_m:'path/to/mother', sv_f:'path/to/father' ]
        gvcfs: List of GVCF files for family trio (proband, mother, father) to be combined, genotyped and annotated
        tbis: Tabix index files for input GVCF files
      pattern: "[ meta, [*.gvcf.gz], [*.tbi] ]"
  - val_fasta:
      type: file
      description: Reference genome FASTA file
      pattern: "*.{fa,fasta}"
  - val_fai:
      type: file
      description: Reference genome FASTA index file
      pattern: "*.{fa.fai,fasta.fai}"
  - val_dict:
      type: file
      description: Reference genome sequence dictionary file
      pattern: "*.dict"

output:
  - vcf:
      type: channel
      description: |
        Channel containing family metadata, final processed VCF file and its tabix index
        Structure: [ meta, vcf, tbi ]
        Where vcf is the final VCF file containing genotyped variants from family trio members 
        after joint calling, variant filtration (LowDepth and LowGQ filters), and removal of unused annotations
        and tbi is the tabix index file for the final VCF
      pattern: "[ meta, *.vcf.gz, *.tbi ]"
          
authors:
  - "@saramenasantamaria"

maintainers:
  - "@saramenasantamaria"